"""add_missing_tables_and_fields

Revision ID: 1fb6a6d54d4c
Revises: f65b241cc3d3
Create Date: 2026-06-14 22:28:15.621809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1fb6a6d54d4c'
down_revision: Union[str, Sequence[str], None] = 'f65b241cc3d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deleted_users_id'), table_name='deleted_users')
    op.drop_table('deleted_users')
    op.drop_index(op.f('ix_deleted_comments_id'), table_name='deleted_comments')
    op.drop_table('deleted_comments')
    op.drop_index(op.f('ix_deleted_posts_id'), table_name='deleted_posts')
    op.drop_table('deleted_posts')
    op.add_column('posts', sa.Column('community_id', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('project_group_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_posts_created_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_user_id'), table_name='posts')
    op.create_foreign_key(None, 'posts', 'communities', ['community_id'], ['id'])
    op.create_foreign_key(None, 'posts', 'project_groups', ['project_group_id'], ['id'])
    op.drop_column('posts', 'likes_count')
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(), nullable=True))
    op.add_column('users', sa.Column('academic_year', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'academic_year')
    op.drop_column('users', 'department')
    op.drop_column('users', 'full_name')
    op.add_column('posts', sa.Column('likes_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_index(op.f('ix_posts_user_id'), 'posts', ['user_id'], unique=False)
    op.create_index(op.f('ix_posts_created_at'), 'posts', ['created_at'], unique=False)
    op.drop_column('posts', 'project_group_id')
    op.drop_column('posts', 'community_id')
    op.create_table('deleted_posts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('original_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('deleted_posts_pkey'))
    )
    op.create_index(op.f('ix_deleted_posts_id'), 'deleted_posts', ['id'], unique=False)
    op.create_table('deleted_comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('original_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('deleted_comments_pkey'))
    )
    op.create_index(op.f('ix_deleted_comments_id'), 'deleted_comments', ['id'], unique=False)
    op.create_table('deleted_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('original_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('avatar_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('deleted_users_pkey'))
    )
    op.create_index(op.f('ix_deleted_users_id'), 'deleted_users', ['id'], unique=False)
    # ### end Alembic commands ###
